# Algorithm design 

## Backtracking 

Backtracking is a technique used to solve optimization problems using different configurations.

In [4]:
import numpy as np

## Auxiliary functions and som conditions
First we need some aux functions to help us with our problem.

In [5]:
A = np.arange(16).reshape(4,4)

In [6]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

How can we get the n-th column of a matrix in numpy

In [7]:
A[2]


array([ 8,  9, 10, 11])

In [8]:
A[:,2]

array([ 2,  6, 10, 14])

How to get a diagonal

In [9]:
diagsR=[(i,A[::-1,:].diagonal(i)) for i in range(-A.shape[0]+1,A.shape[0])]
diagsN=[(i,A.diagonal(i)) for i in range(A.shape[1]-1, -A.shape[1],-1)]

print(diagsR)
print(diagsN)

[(-3, array([0])), (-2, array([4, 1])), (-1, array([8, 5, 2])), (0, array([12,  9,  6,  3])), (1, array([13, 10,  7])), (2, array([14, 11])), (3, array([15]))]
[(3, array([3])), (2, array([2, 7])), (1, array([ 1,  6, 11])), (0, array([ 0,  5, 10, 15])), (-1, array([ 4,  9, 14])), (-2, array([ 8, 13])), (-3, array([12]))]


In [10]:
#Adding a line
print(sum(A[0]))
#Adding a column
print(sum(A[:,0]))

6
24


In [11]:
table = np.zeros((4,4))

# balid table
table[1,1] = 1
table[2,3] = 1
print(table)

diagsR=dict([(i,table[::-1,:].diagonal(i)) for i in range(-table.shape[0]+1, table.shape[0])])
diagsN=dict([(i,table.diagonal(i)) for i in range(table.shape[1]-1, -table.shape[1],-1)])


def get_diagonals(c,N=3):
    """
    Function that returns the correspondant index to the inverted diagonal (diagsR) correspondant to the coordinate C in a 
    table with size 3
    """
    n,m = c
    return m-n, n+m-N



[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [12]:
N, R = get_diagonals((1,1))
print(N,R)
print(diagsN[N])
print(diagsR[R])

0 -1
[0. 1. 0. 0.]
[0. 1. 0.]


In [13]:
print('For the (1,1) point')
n,m = 1,1
sumf, sumc = sum(table[n]), sum(table[:,m])
# We obtain the index's of the dictionary for diagonals
# from point (1,1)
N,R = get_diagonals((n,m))
suman, sumar = sum(diagsN[N]), sum(diagsR[R])
print("Plus line {}, column {}, diagonal {}, daugonal r {}".format(sumf,sumc,suman,sumar))

print("\nFor the point (2,3)")
n,m = 2,3
sumf, sumc = sum(table[n]), sum(table[:,m])

# We obtain the indexes of the dictionary for the diagonals
# point (2,3)
N,R  = get_diagonals((n,m))
suman, sumar = sum(diagsN[N]), sum(diagsR[R])
print('Sum line {}, column {}, diagonal {}, diagonal r {}'.format(sumf,sumc,suman,sumar))

For the (1,1) point
Plus line 1.0, column 1.0, diagonal 1.0, daugonal r 1.0

For the point (2,3)
Sum line 1.0, column 1.0, diagonal 1.0, diagonal r 1.0


In [14]:
# Valid Table
table[1,2] = 1
table

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [15]:
print('For the point in (1,2)')
n,m = 1,2
sumf, sumc = sum(table[n]), sum(table[:,m])
# We obtain the indexes of the dictionary for the diagonals
# of point (1,1)
N,R = get_diagonals((n,m))
suman,sumar = sum(diagsN[N]), sum(diagsR[R])
print('Sum line {}, column {}, diagonal {}, diagonal r {}'.format(sumf,sumc,suman, sumar))

For the point in (1,2)
Sum line 2.0, column 1.0, diagonal 2.0, diagonal r 1.0


In [16]:
def is_valid(T,c,N=3):
    """
    Function that returns True if the coordinate c in the table sums something bigger than 1
    """
    n,m = c
    N,R = get_diagonals(c,N)

    if(sum(T[n])>0):
        #print(1)
        return False
    elif(sum(T[:,m])>0):
        #print(2)
        return False
    elif(sum(diagsN[N])>0):
        #print(3)
        return False
    elif(sum(diagsR[R])>0):
        #print(4)
        return False
    else:
        return True


## Exploration of a state Tree


In [17]:
def tryQueen(n, counter, table): 
    N=  table.shape[0]-1
    if(n==counter):
        return True
    for i in range(n): #We explore the table
        for j in range(n):
            if(is_valid(table, (i,j),N)):
                table[i,j] = 1 # we set a queen 
                counter += 1
                if(tryQueen(n,counter, table)):
                    return True
                table[i,j] = 0 # if it isnt valid
                counter -=1
    return False

In [18]:
table = np.zeros((4,4))
diagsR=dict([(i,table[::-1,:].diagonal(i)) for i in range(-table.shape[0]+1, table.shape[0])])
diagsN=dict([(i,table.diagonal(i)) for i in range(table.shape[1]-1, -table.shape[1],-1)])

In [19]:
tryQueen(4,0,table)

True

In [20]:
table

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])